# Generated by Django 4.2.5 on 2023-10-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='senha',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
